[package]
name = "lulzd"
version = "0.1.0"
authors = ["Lucas Vieira <lucasvieira@protonmail.com>"]
description = "Lulzcoin blockchain synchronization daemon"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
rust-crypto = "0.2.36"